apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          image: sarahmouaci/mon-frontend:latest  # Remplacez par l'image Docker de votre application frontend
          ports:
            - containerPort: 80


