apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  Type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32190
  selector:
    app: prometheus
