apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'my-project'

    rule_files:
      - 'alert.rules'

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 15s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        scrape_interval: 15s
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'redis-exporter'
        scrape_interval: 15s
        static_configs:
          - targets: ['redis-exporter:9121']

      - job_name: 'nodejs-backend'
        scrape_interval: 15s
        static_configs:
          - targets: ['192.168.49.2:32180']

