apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: "redis-master-service.default.svc.cluster.local:6379"

