apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          command:
            - "redis-server"
            - "--appendonly"
            - "yes"  # Active la persistance
